version: '2'

services:
  apache:
    image: bitnami/apache:latest
    ports:
      - 80:8080
    volumes:
      - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
      - .:/app

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=cb37trwso*
    volumes:
      - mariadb_data:/bitnami/mariadb

  php-fpm:
    image: bitnami/php-fpm:latest
    volumes:
      - .:/app

volumes:
  mariadb_data:
    driver: local
